{
  "openapi": "3.0.0",
  "info": {
    "title": "Common User App",
    "description": "This is a sample server for a market shop",
    "version": "1.0.1"
  },

  "servers": [
    {
      "url": "http://localhost:3000/",
      "description": "Local Server"
    }
  ],
  "paths": {
    "/api/user": {
      "post": {
        "description": "Create user",
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/User" }
            },
            "examples": {
              "user": {
                "value": {
                  "name": "Arthur",
                  "password": "12345",
                  "email": "test@gmail.com",
                  "isAdm": false
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "User already exists!"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "user": {
                    "value": {
                      "id": "54f85892-6ad8-4e86-b9a6-e4ebee7d03c8",
                      "name": "Arthur Fenili",
                      "email": "user3@mail.com",
                      "isAdm": true                   
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {}
        ]
      },
      "get": {
        "description": "List all users",
        "tags": ["ADM"],
        "responses": {
          "401": {
            "descripton": "Unauthorized"
          },
          "200": {
            "description": "Ok",
            "content": {
              "schema": {
                "type": "array",
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "user": {
                  "value": [
                    {
                      "id": "26f6a0ec-ee38-473c-b5b2-983e3126ac6a",
                      "email": "user@mail.com",
                      "name": "Arthur",
                      "adm": false,
                      "cart": {
                        "id": "48ff9811-e2d9-4e6c-8a2a-6b039b3aeadc",
                        "products": [
                          {
                            "id": "8b329578-3812-4b4e-bcf2-c28f4a38ba4d",
                            "name": "Heineken 600ml",
                            "price": 6
                          }
                        ]
                      }
                    },
                    {
                      "id": "bf059459-e5b0-457f-9ee5-3925eb6e9b21",
                      "email": "user1@mail.com",
                      "name": "Arthur",
                      "adm": true,
                      "cart": {
                        "id": "6ec12857-3143-4b94-a25a-f480f3a6d72e",
                        "products": []
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/user/{userId}": {
      "get": {
        "description": "List user by id",
        "tags": ["Users"],
        "responses": {
          "401": {
            "descripton":"Unauthorized"
          },
          "200": {
            "description": "OK",
            "content": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/User"
              }
            }
          }
        }
      }
    },
    "/api/login": {
      "post": {
        "description": "Login into application",
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/Login" 
              }
            },
            "examples": {
              "user": {
                "value": {
                  "email": "test@gmail.com",
                  "password": "12345"
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Email or password incorrect"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "access_token": {
                      "type": "string",
                      "readOnly": true
                    }
                  }
                },
                "examples": {
                  "user": {
                    "value": {
                      "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.......-AuocIE0"  
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {}
        ]
      }
    },
    "/api/product": {
      "get": {
        "description": "Select all products",
        "tags": ["Products"],
        "responses": {
          "401": {
            "descripton": "Unauthorized"
          },
          "200": {
            "description": "Ok",
            "content": {
              "schema": {
                "type": "array"
              },
              "examples": {
                "user": {
                  "value": [
                    {
                      "id": "8b329578-3812-4b4e-bcf2-c28f4a38ba4d",
                      "name": "Heineken 600ml",
                      "price": 6
                    },
                    {
                      "id": "b8255e59-41e2-4ba3-803e-71701c9d6799",
                      "name": "Skol 1L",
                      "price": 10
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "Create a new product",
        "tags": ["Products"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/Product" }
            },
            "examples": {
              "product": {
                "value": {
                  "name": "Skol 1L",
                  "price": 10.00
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Product already exists!"
          },
          "201": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Product"
                },
                "examples": {
                  "product": {
                    "value": {
                      "name": "Skol 1L",
                      "price": 10,
                      "id": "b8255e59-41e2-4ba3-803e-71701c9d6799"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/product/{productId}": {
      "get": {
        "description": "Select a product by id",
        "tags": ["Products"],
        "responses": {
          "401": {
            "descripton":"Unauthorized"
          },
          "200": {
            "description": "OK",
            "content": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/Product"
              }
            }
          }
        }
      }
    },
    "/api/cart": {
      "post": {
        "description": "Add a product to user's cart",
        "tags": ["Carts"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": "string",
                  "writeOnly": true
                }
              }
            },
            "examples": {
              "cart": {
                "value": {
                  "name": "Skol 1L"
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unsufficient permission!"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "name": "string",
                    "writeOnly": true
                  }
                },
                "examples": {
                  "user": {
                    "value": "Product Skol 1L added to cart."                
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "description": "Select all carts",
        "tags": ["Carts"],
        "responses": {
          "401": {
            "descripton": "Unauthorized"
          },
          "200": {
            "description": "Ok",
            "content": {
              "schema": {
                "type": "array",
                "$ref": "#/components/schemas/Cart"
              },
              "examples": {
                "cart": {
                  "value": [
                    {
                      "id": "48ff9811-e2d9-4e6c-8a2a-6b039b3aeadc",
                      "products": [
                        {
                          "id": "8b329578-3812-4b4e-bcf2-c28f4a38ba4d",
                          "name": "Heineken 600ml",
                          "price": 6
                        },
                        {
                          "id": "b8255e59-41e2-4ba3-803e-71701c9d6799",
                          "name": "Skol 1L",
                          "price": 10
                        }
                      ]
                    },
                    {
                      "id": "6ec12857-3143-4b94-a25a-f480f3a6d72e",
                      "products": [
                        {
                          "id": "b8255e59-41e2-4ba3-803e-71701c9d6799",
                          "name": "Skol 1L",
                          "price": 10
                        }
                      ]
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/cart/{userId}": {
      "get": {
        "description": "Select user's cart",
        "tags": ["Carts"],
        "responses": {
          "401": {
            "descripton":"Unauthorized"
          },
          "200": {
            "description": "OK",
            "content": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/Cart"
              }
            }
          }
        }
      }
    },
    "/api/cart/{productId}": {
      "delete": {
        "descriptions": "Delete product from user's cart",
        "tags": ["Carts"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "cartId": {
                    "type": "string",
                    "writeOnly": true
                  }
                }
              }
            },
            "examples": {
              "cartid": {
                "value": {
                  "cartId": "48ff9811-e2d9-4e6c-8a2a-6b039b3aeadc"
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "descripton":"Unauthorized"
          },
          "204": {
            "description": "OK"
          }
        }
      }
    },
    "/api/buy": {
      "post": {
        "description": "Finish purchase",
        "tags": ["Purchase"],
        "responses": {
          "400": {
            "descripton":"Error"
          },
          "200": {
            "description": "OK",
            "content": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/Purchase"
              },
              "examples": {
                "purchase": {
                  "value": {
                    "purchase_owner": "bf059459-e5b0-457f-9ee5-3925eb6e9b21",
                    "purchase_owner_email": "user1@mail.com",
                    "purchase_owner_name": "Arthur",
                    "purchase_products": [
                      {
                        "id": "b8255e59-41e2-4ba3-803e-71701c9d6799",
                        "name": "Skol 1L",
                        "price": 10
                      }
                    ],
                    "purchase_id": "d103fd47-24c1-463f-a332-45648d380ccb"                   
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "description": "Select all purchases",
        "tags": ["Purchase"],
        "responses": {
          "401": {
            "descripton": "Unauthorized"
          },
          "200": {
            "description": "Ok",
            "content": {
              "schema": {
                "type": "array",
                "properties": {
                  "id": {
                    "type": "string",
                    "readOnly": true
                  },
                  "purchasedAt": {
                    "type": "string",
                    "readOnly": true
                  },
                  "cart_id": {
                    "type": "string",
                    "readOnly": true
                  }
                }
                
              },
              "examples": {
                "purchase": {
                  "value": [
                    {
                      "id": "d8caf7c8-4e59-45fe-a310-be4ab11615f9",
                      "purchasedAt": "2022-02-03T01:25:55.890Z",
                      "cart_id": "6ec12857-3143-4b94-a25a-f480f3a6d72e"
                    },
                    {
                      "id": "12a28659-3ebe-4cf7-912f-b6889cb2b9df",
                      "purchasedAt": "2022-02-03T01:26:47.650Z",
                      "cart_id": "6ec12857-3143-4b94-a25a-f480f3a6d72e"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/buy/{purchaseId}": {
      "get": {
        "description": "Select a specific purchase",
        "tags": ["Purchase"],
        "responses": {
          "401": {
            "descripton": "Unauthorized"
          },
          "200": {
            "description": "Ok",
            "content": {
              "schema": {
                "type": "object",
                "properties": {
                  "purchase": {
                    "type": "object",
                    "readOnly": true
                  },
                  "purchase_products": {
                    "type": "array",
                    "readOnly": true
                  }
                }
              },
              "examples": {
                "purchase": {
                  "value": {
                    "purchase": {
                      "id": "d8caf7c8-4e59-45fe-a310-be4ab11615f9",
                      "purchasedAt": "2022-02-03T01:25:55.890Z",
                      "cart_id": "6ec12857-3143-4b94-a25a-f480f3a6d72e"
                    },
                    "purchase_products": [
                      {
                        "id": "b8255e59-41e2-4ba3-803e-71701c9d6799",
                        "name": "Skol 1L",
                        "price": 10
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/email": {
      "post": {
        "description": "Send an email",
        "tags": ["ADM"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "email": {
                    "type": "string",
                    "writeOnly": true
                  }
                }
              }
            },
            "examples": {
              "email": {
                "value": {
                  "email": "test@gmail.com"              
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Error!"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "from": {
                      "type": "string",
                      "readOnly": true
                    },
                    "to": {
                      "type": "array",
                      "readOnly": true
                    }
                  }
                },
                "examples": {
                  "user": {
                    "value": {
                      "from": "arthur.linemburg@unesc.net",
                      "to": [
                        "user@mail.com"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/recuperar": {
      "post": {
        "description": "Send a recovery code to user's email",
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "email": {
                    "type": "string",
                    "writeOnly": true
                  }
                }
              }
            },
            "examples": {
              "email": {
                "value": {
                  "email": "test@gmail.com"              
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Error!"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "type": "string",
                    "readOnly": true
                  }
                },
                "examples": {
                  "value": "Recovery code sent successfully"
                }
              }
            }
          }
        }
      }
    },
    "/api/alterar_senha": {
      "post": {
        "description": "Change user's password by his recovery code",
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "recovery_code": {
                    "type": "string",
                    "writeOnly": true
                  },
                  "new_password": {
                    "type": "string",
                    "writeOnly": true
                  }
                }
              }
            },
            "examples": {
              "change_pass": {
                "value": {
                  "recovery_code": "2649",
                  "new_password": "102030"
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Error!"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "type": "string",
                    "readOnly": true
                  }
                },
                "examples": {
                  "value": "Password changed successfully"
                }
              }
            }
          }
        }
      }
    }
  },

  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "readOnly": true
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string",
            "writeOnly": true
          },
          "isAdm": {
            "type": "boolean"
          }
        }
      },
      "Login": {
        "type":"object",
        "properties": {
          "email": {
            "type": "string",
            "writeOnly": true
          },
          "password": "string",
          "writeOnly": true
        }
      },
      "Product": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "readOnly": true
          },
          "name": {
            "type": "string"
          },
          "price": {
            "type": "string"
          }
        }
      },
      "Cart": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "readOnly": true
          },
          "products": [
            {
              "id": "string",
              "name": "string",
              "price": "number"
            }
          ]
        }
      },
      "Purchase": {
        "type": "object",
        "properties": {
          "purchase_owner": {
            "type": "string",
            "readOnly": true
          },
          "purchase_owner_email": {
            "type": "string",
            "readOnly": true
          },
          "purchase_owner_name": {
            "type": "string",
            "readOnly": true
          },
          "purchase_products": {
            "type": "array",
            "readOnly": true
          },
          "purchase_id": {
            "type": "string",
            "readOnly": true
          }
        }
      }
    },
    "securitySchemes": {
      "JWT": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "security": [
    {
      "JWT": []
    }
  ]
} 